# Generated by Django 3.1.2 on 2020-11-24 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20201124_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_major', models.CharField(max_length=255)),
                ('award', models.CharField(blank=True, max_length=255)),
                ('experience', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
